### ISSUE TITLE
Ableton Usability Issue  

### ISSUE THREAD

**Issue by ghost** [wolf-plugins/wolf-shaper#152] opened 2021-06-30 10:14 UTC
I am using Ableton live 9 on Windows which accepts vst2 plugins but when I load Wolf-Shaper, all I get is a black square as the plugin and ableton instantly shuts down. I tried using previous versions but that ended up shutting my entire computer off. If you need any more information or have information on how to fix this, please let me know.

**Comment by pdesaulniers** [comment] 2021-06-30 11:25
Can you please test this build and see if you can still reproduce the issue? [wolf-shaper-vst-d2466f3.zip](https://github.com/wolf-plugins/wolf-shaper/files/6740404/wolf-shaper-vst-d2466f3.zip)

Otherwise, I'll see if I can reproduce the issue on my side.

**Comment by Asotus** [comment] 2021-06-30 11:42
I just tried it out right now. Although it does not crash now when I open it, it still shows up at as blank black screen. I have the orginal crash report of the previous version. If you would like me to send it, I can do it now.

**Comment by pdesaulniers** [comment] 2021-06-30 12:51
>  I have the orginal crash report of the previous version. If you would like me to send it, I can do it now.

Yes, please send the crash report :)

**Comment by Asotus** [comment] 2021-06-30 13:03
Ok, it is attached here.
[Ableton Crash Report 2021-06-30 030514 Live 9.7.7.zip](https://github.com/wolf-plugins/wolf-shaper/files/6741063/Ableton.Crash.Report.2021-06-30.030514.Live.9.7.7.zip)

**Comment by pdesaulniers** [comment] 2021-06-30 13:06
Thanks! I'll take a look at this.

**Comment by pdesaulniers** [comment] 2021-09-18 15:44
I cannot reproduce this issue anymore on latest DPF. I think it's a matter of pushing a new release.

**Comment by pdesaulniers** [comment] 2022-12-29 22:28
Should be fixed in the latest release!

**Closed by pdesaulniers** 2022-12-29 22:28 UTC
Labels: bug, windows
